package dev.lgbonillar.regreporting.upload.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDateTime;
import java.util.UUID;

@Schema(description = "Uploaded report file metadata.")
public record UploadedFileResponse(
        @Schema(description = "Uploaded file identifier.")
        UUID fileId,

        @Schema(description = "Original uploaded filename.", example = "capital-requirements-jan.xlsx")
        String originalFilename,

        @Schema(description = "Stored filename generated by the backend.")
        String storedFilename,

        @Schema(description = "Detected or provided content type.")
        String contentType,

        @Schema(description = "File size in bytes.", example = "125000")
        long fileSize,

        @Schema(description = "SHA-256 checksum of the stored file.")
        String checksum,

        @Schema(description = "Current file status.", example = "STORED")
        String fileStatus,

        @Schema(description = "Username that uploaded the file.", example = "analyst01")
        String uploadedBy,

        @Schema(description = "Timestamp when the file was uploaded.")
        LocalDateTime uploadedAt,

        @Schema(description = "Timestamp when the file metadata was last updated.")
        LocalDateTime updatedAt
) {
}
